# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: tide-jon <tide-jon@student.codam.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2019/03/20 20:56:58 by tide-jon       #+#    #+#                 #
#    Updated: 2019/03/20 21:13:41 by tide-jon      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

all: ft_display_file

ft_display_file:
	gcc -Wall -Wextra -Werror -c ft_display_file.c
	gcc -o ft_display_file ft_display_file.o

clean:
	rm -f ft_display_file.o

fclean: clean
	rm -f ft_display_file
